### ISSUE TITLE
Base speed being modified leading to incorrect speeds.

### ISSUE THREAD

**Issue by ianblackstone** [Doctor-Unspeakable/foundry-pathbuilder2e-import#15]
When importing a high level character the base speed is being brought in with any modifications such as from the constant effects of Swashbuckler vivacious speed or Monk incredible movement.  A level 7 monk imports with a 40 foot base move speed, but since Foundry automates the speed bonuses of those abilities now so it leads to double dipping these speed bonuses.  Pathbuilder also does not round the speed from vivacious speed down into 5 foot increments, leading to characters with 37 foot move speeds.  This should be scrubbed.  The issue is fixed by replacing the ancestry with one of the compendium versions.

**Comment by Doctor-Unspeakable** [comment]
I've fixed the Vivacious Speed rounding issue for the next publish.

I've run into a difficulty though with exporting the speed though.  Foundry automates some of the speed bonuses - eg Vivacious Speed, but not others, like Fleet and Nimble Elf.  At the export stage Pathbuilder 2e cannot distinguish between the class feature speed increases that Foundry seems to be automating and feat speed increases that Foundry does not automate.  I'm going to pass this issue onto them, but until they automate everything I'm stuck in the middle - if I remove the speed bonuses then people will put in bug reports about Fleet and Nimble Elf.

**Comment by Doctor-Unspeakable** [comment]
I spoke to the foundry guys and although the feat speed increases aren't implemented at the moment, they will be soon, so I've removed any bonus speed calculation from the import with the next Pathbuilder publish.
