### ISSUE TITLE
The import creates custom ancestries and classes rather than using those already in the compendium.

### ISSUE THREAD

**Issue by plglsn** [Doctor-Unspeakable/foundry-pathbuilder2e-import#16]
I wanted to check if there is any plan to change this?

Right now if a character is imported from pathbuilder you have to go through a lot of extra work to level it up within foundry. If the classes from the compendium were used new class features are unlocked once you update the characters level.

**Comment by Doctor-Unspeakable** [comment]
Yes, I'm going to update the importer after the next Pathbuilder 2e publish.  They've also added classes and feats with level slots, so the app needs to export extra data to fill that in.
