### ISSUE TITLE
Importing a character via Foundry bug.

### ISSUE THREAD

**Issue by Thrandull** [Doctor-Unspeakable/foundry-pathbuilder2e-import#17]
I've been uploading a lot of characters, and this is the only one that I've had issues with. I've tried on a new server etc. but still get the same issue.
It seems to upload ok, but then when I click on the spells tab in the foundry character sheet, Foundry freezes and take a long time to load the screen with missing spells. Even once the spells are moved/deleted it's still unplayable slow.

Other than that, thanks so much for such an amazing app.

 http://www.pathbuilder2e.com/launch.html?build=49612

[elven priest.zip](https://github.com/Doctor-Unspeakable/foundry-pathbuilder2e-import/files/6174818/elven.priest.zip)

**Comment by Thrandull** [comment]
Just to add, a similar issue happens with the feats and items pages - again just on this 1 character of the many I've imported. I tried re exporting it from Pathbuilder, but got the same issue. Sometimes those pages load, often they don't, and most of the information is missing. (Or possibly all, depending on how much Foundry adds from knowing the class and level)

**Comment by Doctor-Unspeakable** [comment]
What version of foundry and the pathfinder 2e modules are you using?

**Comment by Kriptini** [comment]
Hi, I want to report that I am having this issue as well, and it's getting to the point where it makes the entire server crash on import. I can work around it by waiting several minutes, shutting down the server, and then relaunching the server, but it's highly inconvenient. Here's a Foundry import code for the troublesome character (I'll try to get a permanent share link from the player ASAP): 103403.

Foundry version: 0.7.9
Pathbuilder 2e Import version: 0.1.18
