### ISSUE TITLE
Stowed Armor and some items won't transfer

### ISSUE THREAD

**Issue by Unikatze** [Doctor-Unspeakable/foundry-pathbuilder2e-import#2]
Stowed items won't transfer over. I assume this is because the names in Pathbuilder don't match what's in the compendium in foundry. Such as "+1 Chain Mail (Stowed)"

Another item was Oil.  
Named "Oil" in Pathbuilder and"Oil (1 pint)" in foundry. 

Custom items such as scrolls won't transfer either. I'm not sure if there's even a possible solution to that.

**Comment by Doctor-Unspeakable** [comment]
Hi. 
I've added support for the stowed items, in the next pathbuilder publish and module upgrade.

Many items will not match unfortunately.  There is a note in the import dialog in foundry saying that (and that custom items will not import).  Basically if a match in the foundry database isn't found, then it won't get added.  However, I've added a dialog at the end of the import process that will list the failed items to the user so they can attempt a manual search.
