### ISSUE TITLE
FoundryVTT updated, broke pathbuilder plugin. 

### ISSUE THREAD

**Issue by kaffien** [Doctor-Unspeakable/foundry-pathbuilder2e-import#23]
Foundry is now updated to 0.8.6 stable release. 
This seems to have 'broken' the pathbuilder2e-import. 

Hopefully its not a big fix.  I was just onboards a whole new group of players hehe.

**Comment by Doctor-Unspeakable** [comment]
They broke pretty much all of it.  Was a massive fix.  I've got most of it
working apart from spells which I've had to disable.

I'll have a look at that when I've got more time.

**Comment by kaffien** [comment]
Thank you, 

I can't wait.  Do you have a patreon / buy you a coffee etc?

**Comment by Unikatze** [comment]
> Thank you,
> 
> I can't wait. Do you have a patreon / buy you a coffee etc?

https://www.patreon.com/redrazors/

**Comment by kaffien** [comment]
I dropped you a few bucks. Hopefully you're able to find some time to fix the rest. 
I have a bunch of people all hopped up on how awesome pathbuilder2e is and we kind of stalled out on our foundryvtt
game. 

Have a good day and enjoy the sunshine!

**Comment by Doctor-Unspeakable** [comment]
Did the update go through normally?  When I fixed it I had to mess around with the packages and was concerned that people would need to reinstall the module to get the latest version.

**Comment by Doctor-Unspeakable** [comment]
I had another go at spells today.  Cannot see how to make it work at all, so they may be disabled indefinitely.
