### ISSUE TITLE
Unchecking "Import Inventory" Causes Inventory To Be Wiped

### ISSUE THREAD

**Issue by nrllewellyn** [Doctor-Unspeakable/foundry-pathbuilder2e-import#26]
(Issues are disabled on the @zarmstrong fork, so hopefully this is the correct place to post issues!)

If you uncheck the "Import Equipment?" box during the import process, the character's inventory is cleared. (Expected behavior is that existing items would be left untouched.)

Tested with:
Foundry: 0.8.8
Pathbuilder 2e Importer: 0.6.2

**Comment by zarmstrong** [comment]
I might have to disable that feature for now. Most things on a pc are stored as items, and there were a lot of issues with items corrupting PCs when you import over an existing PC. 

Longer term, it should work, but for now it's kinda in a funky state.

**Comment by zarmstrong** [comment]
I've corrected the issues not working on my fork. Feel free to recreate this issue there :)

**Comment by nrllewellyn** [comment]
Moved to https://github.com/zarmstrong/foundry-pathbuilder2e-import/issues/2
