### ISSUE TITLE
Background and Deity Don't Import Correctly

### ISSUE THREAD

**Issue by nrllewellyn** [Doctor-Unspeakable/foundry-pathbuilder2e-import#27]
(Issues are disabled on the @zarmstrong fork, so hopefully this is the correct place to post issues!)

Deity doesn't import from PathBuilder 2e's "About" page
Background doesn't import from the "Build" page.

Tested with:
Foundry: 0.8.8
Pathbuilder 2e Importer: 0.6.2

**Comment by zarmstrong** [comment]
Thanks I'll see if we can get issue reporting fixed. 

Can you provide the PC # you're having trouble with?

**Comment by zarmstrong** [comment]
Deity not importing is covered by #19

**Comment by zarmstrong** [comment]
I've also corrected the issues not working on my fork. Feel free to recreate this issue there :)

**Comment by nrllewellyn** [comment]
Not sure how I missed #19. Ticket closed. :-)

**Comment by nrllewellyn** [comment]
Missed #19 somehow. (D'oh!)

Example character: 107055. Will make an equivalent ticket on your fork, just to make things easier :-)

**Comment by nrllewellyn** [comment]
Moved to https://github.com/zarmstrong/foundry-pathbuilder2e-import/issues/3
