### ISSUE TITLE
Ancestral Paragon > Arcane Tattoo > Tanglefoot import error

### ISSUE THREAD

**Issue by VeilOfOblivion** [Doctor-Unspeakable/foundry-pathbuilder2e-import#4]
Hi team,

Importing a character with Ancestral Paragon > Arcane Tattoo > Tanglefoot causes an error:

```
The following items did not find a match in the Foundry database and could not be added. You may be able to find them with a manual search. 
Special: Tanglefoot
```

Foundry version: 0.6.6 (stable)
PF2e version: 1.10.14.2141
Other modules active: none (deactivated all to test this) 

Please let me know if you need any further details.

Thorsten

**Comment by Doctor-Unspeakable** [comment]
Hi, this isn't actually an error. as it says in the description when you start the import, it won't match everything.  It's for your info only, as sometimes it may be a generated item which you do want to add manually.

**Comment by VeilOfOblivion** [comment]
Sounds good. Thanks. It actually added the Tanglefoot spell as an innate spell. So all good there. But thank you for building this. Great addition to Foundry and Pathbuilder!
