### ISSUE TITLE
Importing custom items

### ISSUE THREAD

**Issue by MikeBrightman** [Doctor-Unspeakable/foundry-pathbuilder2e-import#5]
When importing items, it obviously doesn't recognise any custom items created in-app. However, since Foundry supports custom items, it would be possible to auto-create items if they have been properly defined by the user in pathbuilder.

I'm not sure how much effort this would be, I imagine it's very possible but without having made Foundry plugins I don't want to assume. And, the "custom" tag would mean that those who don't want to import an item can simply not have it be imported, or alternatively offer a dialogue asking if a custom item should be created. But since actions can be associated with custom items, I imagine it could also auto-populate the available actions page on the character sheet.

Thoughts?

**Comment by Doctor-Unspeakable** [comment]
I think it might be possible, not sure about creating custom actions though linked to the equipment.

I'm short of time for this sort of thing and it's a fairly big task so I'm going to leave it open just now,
