### ISSUE TITLE
Ancestry traits not transferring. 

### ISSUE THREAD

**Issue by Unikatze** [Doctor-Unspeakable/foundry-pathbuilder2e-import#7]

**Comment by Doctor-Unspeakable** [comment]
I don't understand this.  Please provide specific information.

**Comment by Unikatze** [comment]
> I don't understand this. Please provide specific information.

I mean Ancestry traits. For example, if I'm a Human Half/Elf I'll have the Human and the Elf Traits. 
![image](https://user-images.githubusercontent.com/43307189/100276609-cdf0a280-2f2f-11eb-882b-51b8813fdd44.png)

**Comment by Doctor-Unspeakable** [comment]
I've decided to leave this alone. I can't reliably add in the heritages are they are not all listed and if I do it badly it will overwrite whatever users have entered themselves.  It's a small matter and quite easy for those that care to fix themselves (I don't think I've ever set traits in my characters).
