### ISSUE TITLE
Dueling Feats don't convert

### ISSUE THREAD

**Issue by pearcebasmanm** [Doctor-Unspeakable/foundry-pathbuilder2e-import#9]
The feats Dueling Parry and Dueling Dance don't convert.
I suspect that this is because Pathbuilder calls both the fighter and swashbuckler versions Dueling Parry and Dueling Dance, while Foundry refers to them as Dueling Parry (Fighter), Dueling Parry (Swashbuckler), Dueling Dance (Fighter), and Dueling Dance (Swashbuckler).

I haven't tested this, but the same problem might also arise with other feats that have slightly different versions between classes.

![image](https://user-images.githubusercontent.com/75871317/101973344-67dd6e00-3c05-11eb-81c8-dbb6e1b3fe03.png)
![image](https://user-images.githubusercontent.com/75871317/101973383-a70bbf00-3c05-11eb-8cb6-05058c2192aa.png)
PS: I made the character to double-check it was just the feats, and there wasn't another cause. That's why the level 20 character doesn't have other feats.

**Comment by Doctor-Unspeakable** [comment]
OK I've added a system to check for dueling parry (classname) which should fix it in most cases (but not for archetype fighters).
